joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0




drone_cont_teleop_node:
  ros__parameters:
    axis_linear:
      x: 0 #Left thumb stick Horizo
    scale_linear:
      x: 2.0
    scale_linear_turbo:
      x: 6.0

    axis_linear:
      y: 1 #Left thumb stick vertical
    scale_linear:
      y: 2.0
    scale_linear_turbo:
      y: 6.0

    axis_angular:
      yaw: 3 #right thumb stick Vertical
    scale_angular:
      yaw: 2.0
    scale_angular_turbo:
      yaw: 4.0

    
    require_enable_button: true
    enable_button: 6 # Left shoulder button
    enable_turbo_button: 7 # Right shoulder button

diffdrive_teleop_node:
  ros__parameters:
    axis_angular:
      yaw: 2 #Left thumb stick vertical
    axis_angular:
      yaw: 2.0
    scale_angular_turbo:
      yaw: 6.0
    
    require_enable_button: true
    enable_button: 6 # Left shoulder button
    enable_turbo_button: 7 # Right shoulder button